### ISSUE TITLE
检测僵尸粉的代码无效

### ISSUE THREAD

**Issue by sudami** [skyun1314/WeChat-plug-in#1]
查询到的数据库有几点问题：

1. 好友数量不正确，还算上了“公众号”
2. contactLabelIds 一直为空，导致无法确定当前好友的类型

所以单纯的查询数据库好像是无法确定当前好友状态的，有一个APK实现了零打扰检测僵尸粉，原理：
**1. 枚举数据库，得到所有好友的ID
2. 启线程循环调用 微信内部添加好友的函数，把每个好友再添加一遍
3. hook 微信内某函数，在每个已添加该好友的窗口，判断是否被拉黑/删除
4. 好友是不会收到任何消息的，也就是零打扰**

要不你也这样尝试一下吧~

![_20180412131124](https://user-images.githubusercontent.com/6194926/38657487-06ff17a8-3e53-11e8-9e57-65d2949e9a48.png)

**Comment by skyun1314** [comment]
@sudami 好的。谢谢。。
