### ISSUE TITLE
可以跳过开发6.6.6版本直接出6.6.7版本的了

### ISSUE THREAD

**Issue by fireson-gor** [skyun1314/WeChat-plug-in#10]
刚刚装了6.6.7版本的微信，发现界面和功能都真正意义上的改变了（多了微信悬浮圈等），但插件失效了，希望强大的作者直接先开发6.6.7版本的。还有希望加一个朋友圈自动点赞功能和自动加附近的人为好友功能就完美了。可以参考其他插件作者的代码，哈哈哈，不说了，卸载6.6.7版微信重装去了。😀😎

**Comment by fireson-gor** [comment]
附上6.6.7版本微信下载链接，需要微信里打开🔗https://support.weixin.qq.com/cgi-bin/mmsupport-bin/readtemplate?t=page/android_exp__index&amp;clientversion=

**Comment by skyun1314** [comment]
微信效率太高了。又出了6.6.7 我6.6.6都没有兼容。不说了。赶紧体验一下

**Comment by skyun1314** [comment]
哥们留个qq。探讨一下。我没有发现哪里不一样啊

**Comment by brooklf** [comment]
6.6.6的发送消息接口变了点，不知道6.6.7的时什么样的

**Comment by skyun1314** [comment]
更新了667
