### ISSUE TITLE
这个到底要怎么使用

### ISSUE THREAD

**Issue by magiccubehb** [skyun1314/WeChat-plug-in#16]
打开界面只有帮助文档，没有任何按钮。。。。请问我该怎么使用

**Comment by skyun1314** [comment]
xposed勾选重启。微信里面有入口

**Comment by magiccubehb** [comment]
解决了，竟然是不支持向下兼容，升级6.6.7才能用

**Comment by skyun1314** [comment]
嗯嗯。只兼容66.7和661

**Comment by Ortu** [comment]
大牛能不能说下怎么在virtual xposed进设置界面。我在里面外面都装好了1.7的插件版本，设置也一样，virtualxposed也打勾重启了，但是还出现不到功能界面

**Comment by ViceTe** [comment]
同上Ortu的状况

**Comment by lighterEB** [comment]
请问安卓8.1修改步数微信运动不生效是什么原因

**Comment by skyun1314** [comment]
他是累加的可能有延迟。等等看
