### ISSUE TITLE
小米5s，VirtualXposed，微信6.67，怎么不好使啊？

### ISSUE THREAD

**Issue by zerowinning** [skyun1314/WeChat-plug-in#18]
里面装，外面装，重启VXposed，重启微信，重启手机都没什么用。
使我那个步骤没做好吗？能否简单写一个操作步骤？

**Comment by ViceTe** [comment]
同样的情况，里面装，勾选组件，重启VXP，重启微信；外面装但没有设置选项，只能打开软件，也没有1.7关于VXP的提示。请教一下步骤，谢谢skyyun大！

**Comment by HarryDean2010** [comment]
小米6，VirtualXposed，操作同2楼，一样的不起任何作用。不同的是外面装的那个打开就是使用帮助和设置界面。进微信里没有任何设置的地方和提示。

**Comment by skyun1314** [comment]
各位兄弟不好意思我自己的问题。插件有问题。最近在加新功能。所以呆几天一起修复发布
