### ISSUE TITLE
修改步数应该怎么正确使用？

### ISSUE THREAD

**Issue by lighterEB** [skyun1314/WeChat-plug-in#21]
更改了步数在微信运动里没有刷新。
微信版本6.6.7
ROM是lineageOS15.1
系统android 8.1

**Comment by skyun1314** [comment]
步数是累加的。有延迟。等等看

**Comment by lighterEB** [comment]
累加期间需要频繁打开微信吗，另外会经常显示微信已经停止，虽然不知道影响了什么。

**Comment by lighterEB** [comment]
我发现该步数10点以后才生效

**Comment by skyun1314** [comment]
能生效就ok
