### ISSUE TITLE
导致语音发不出去

### ISSUE THREAD

**Issue by kanakey** [skyun1314/WeChat-plug-in#4]
一直显示正在发送，有时候等几分钟才发出去，文字没毛病，好像这是微信助手就有这毛病

**Comment by skyun1314** [comment]
好的，等下我测试下

**Comment by kanakey** [comment]
新版解决了吗大佬

**Comment by skyun1314** [comment]
我刚测试。应该没有问题了。我在发布一个版本，你试试。谢谢关注

**Comment by kanakey** [comment]
发布在xposed那里吗，我去试下

**Comment by skyun1314** [comment]
我刚又重新测试了一下，语音图片视频，都支持测回。不过，现在发送这块还是有问题。不知道什么触发的。

**Comment by skyun1314** [comment]
靠，哥们，你测试点真细致，确实有问题。界面显示防止图片，视频语音撤回了，但是就打不开了

**Comment by kanakey** [comment]
对啊，只有文字有效，xposed仓库另外一个微信增强的模块可以有效单子撤回，语音、图片、视频都可以

**Comment by kanakey** [comment]
整好没有大佬

**Comment by skyun1314** [comment]
整好了啊。你用的是不是最新的1.4版

**Comment by kanakey** [comment]
支持微信6.6.6没

**Comment by skyun1314** [comment]
没有支持呢。我现在想把6.6.1的全部功能都做完了再说

**Comment by skyun1314** [comment]
支持6.6.1和667修复各种bug
