### ISSUE TITLE
微信6.6.7和7.0，点了畅玩里面的设置只是打开微信，并没有弹出设置界面

### ISSUE THREAD

**Issue by chinese-tea** [skyun1314/WeChat-plug-in#51]
微信6.6.7和7.0，点了畅玩里面的设置只是打开微信，并没有弹出设置界面，是什么原因？xp框架是用的2.7

**Comment by fireson-gor** [comment]
同样的问题，太极＋微信70，显示加载插件完成，微信右上角不显示切入界面的图标，无法进入设置页面。

**Comment by skyun1314** [comment]
畅玩酷安更新到最新.太极更新到最新
