### ISSUE TITLE
一加5 lineageOS android8.1 激活后仍然显示未激活

### ISSUE THREAD

**Issue by monkey000** [skyun1314/WeChat-plug-in#52]
用的是magisk 的非官方版xposed框架
微信7.0

![503538761](https://user-images.githubusercontent.com/36021889/51593695-c0ca8d00-1f2d-11e9-9590-c2170471f71d.jpg)
![385574053](https://user-images.githubusercontent.com/36021889/51593548-5fa2b980-1f2d-11e9-9495-178a15be8b31.jpg)
![661226417](https://user-images.githubusercontent.com/36021889/51593550-5fa2b980-1f2d-11e9-8654-4acbdff237dd.jpg)
![963130555](https://user-images.githubusercontent.com/36021889/51593551-603b5000-1f2d-11e9-83f5-8c268335db0d.jpg)
![1265826670](https://user-images.githubusercontent.com/36021889/51593552-603b5000-1f2d-11e9-930e-87a227b9d8c9.jpg)

**Comment by skyun1314** [comment]
太极没有激活无所谓啊.xvp加载了就行了
