### ISSUE TITLE
被封账号了 weixin7.0 (T_T)

### ISSUE THREAD

**Issue by rancpine** [skyun1314/WeChat-plug-in#54]
怎么办啊，搞了一下午，找了个大号申诉解封的； xposed framework: 89; 畅玩微信plugin: 1.8.8.5

**Comment by rancpine** [comment]
我是直接安装的xposed framework

**Comment by zyx2813467705** [comment]
可怕。。

**Comment by rancpine** [comment]
> 可怕。。

给我郁闷坏了

**Comment by skyun1314** [comment]
怎么了

**Comment by skyun1314** [comment]
其他模块都关了

**Comment by rancpine** [comment]
对啊  就只装了一个这个模块


2019-01-29 13:46 GMT+08:00, skyun1314 <notifications@github.com>:
