### ISSUE TITLE
源代码打的apk，在Vxp中，微信没有进入设置入口。

### ISSUE THREAD

**Issue by coyoo** [skyun1314/WeChat-plug-in#58]
下载了源代码打的apk包，在Vxp中，安装完点开只显示定位的，而微信里没有能进入设置的入口。而源代码里的那个微信加强的apk，又是能用的。
源代码是要做什么改动，微信才能显示设置入口呢？

**Comment by coyoo** [comment]
好像少一个MyApplication.iml文件，o(╥﹏╥)o

**Comment by coyoo** [comment]
vxp版本是0.16.1，微信版本6.6.1

**Comment by skyun1314** [comment]
你看看日志呗
