### ISSUE TITLE
最新版无法链接服务器下载更新文件

### ISSUE THREAD

**Issue by brucelian** [skyun1314/WeChat-plug-in#59]
刚刚从酷安下载最新版 1887，打开设置显示：

> 无法链接服务器下载更新文件
>1.1.3 skyun1314@gmail.com(c)
> ...

手机红米5，Android 7.1.2，Xposed 89，微信7.0.0

**Comment by skyun1314** [comment]
重置模块.杀死微信.重新勾选.重启手机
