### ISSUE TITLE
能否把抢红包功能加上一个只提示不自动抢的开关

### ISSUE THREAD

**Issue by meetinnet** [skyun1314/WeChat-plug-in#6]
。。。。。。。

有些群的有些人的红包不想抢，有些时间段的红包不能抢，定制需求太多，能否加上这个只提示有红包(语音，震动，弹框可选)，不自动抢的开关，这样也降低了腾讯封号的风险。

.

**Comment by skyun1314** [comment]
等我有时间在做。最近事很多

**Comment by vipzrx** [comment]
@meetinnet 
> 有些群的有些人的红包不想抢，
功能 排除好友和群

>有些时间段的红包不能抢
排除功能时段

>，定制需求太多，能否加上这个只提示有红包(语音，震动，弹框可选)，
这个是红包的提示

>不自动抢的开关
排除特定好友和群

>，这样也降低了腾讯封号的风险。
 红包设置排除关键词, 设置随机延迟 墙红包之后的自动回复语
