### ISSUE TITLE
华为mate20一点表情包就闪退

### ISSUE THREAD

**Issue by zzhi0** [skyun1314/WeChat-plug-in#61]
下面是virtual xposed的日志

03-24 12:35:28.798 I/VClientImpl(12637): Binding application com.tencent.mm, (com.tencent.mm:appbrand0)
03-24 12:35:28.842 I/VClientImpl(12637): Xposed is enabled.
03-24 12:35:29.028 I/VClientImpl(12662): Binding application com.tencent.mm, (com.tencent.mm:tools)
03-24 12:35:29.053 I/VClientImpl(12662): Xposed is enabled.
03-24 12:35:31.073 E/VClientImpl( 7071): 
03-24 12:35:31.202 I/ExposedBridge(12637): com.tencent.mm is not a Xposed module, do not init epic.force
03-24 12:35:31.203 I/ExposedBridge(12637): module:/data/user/0/io.va.exposed/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
03-24 12:35:31.203 I/ExposedBridge(12637): module:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk is disabled, ignore
03-24 12:35:31.203 I/ExposedBridge(12637): Loading modules from /data/user/0/io.va.exposed/virtual/data/app/com.example.wx_plug_in3/base.apk for process: com.tencent.mm:appbrand0 i s c: false
03-24 12:35:31.223 I/Xposed  (12637): ignor

**Comment by skyun1314** [comment]
最新版修复了
