### ISSUE TITLE
朋友圈小号自动跟随大号转发朋友圈

### ISSUE THREAD

**Issue by Girlex** [skyun1314/WeChat-plug-in#65]
希望能有单独的朋友圈转发插件，不需要那么多额外的功能，
或者现在也挺好的，朋友圈小号跟随大号转发，希望大神加油哦！

**Comment by skyun1314** [comment]
谢谢

**Comment by Girlex** [comment]
请问现在实现了没

在 2019-07-08 10:28:38，"skyun1314" <notifications@github.com> 写道：


谢谢
