### ISSUE TITLE
1.2.7 内核开启"归拢公用号"会闪退

### ISSUE THREAD

**Issue by brucelian** [skyun1314/WeChat-plug-in#69]
软件版本是1.8.8.9。前几天升级了内核，然后发现原先归拢的微信公众号又在列表页排开了。重新点击"归拢公众号"按钮会闪退。

红米 MIUI10
Android 7.1.4
微信 7.0.4

xposed 日志如下：
06-20 12:55:54.783 E/Xposed  (14475): java.lang.NoSuchMethodError: com.tencent.mm.ui.chatting.y#onCreateOptionsMenu(android.view.Menu,android.view.MenuInflater)#exact
06-20 12:55:54.783 E/Xposed  (14475): 	at de.robv.android.xposed.XposedHelpers.findMethodExact(XposedHelpers.java:344)
06-20 12:55:54.783 E/Xposed  (14475): 	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:185)
06-20 12:55:54.783 E/Xposed  (14475): 	at com.android.wechat.ᐝᵢ.ˊˋ.ˎˋ(gb:456)
06-20 12:55:54.783 E/Xposed  (14475): 	at com.android.wechat.Main.handleLoadPackage(gn:156)
06-20 12:55:54.783 E/Xposed  (14475): 	at com.example.zhang.myapplication.Main.NativeinvokeHandleHookMethod(Native Method)
06-20 12:55:54.783 E/Xposed  (14475): 	at com.example.zhang.myapplication.InitHook.ALLATORIxDEMO(o:186)
06-20 12:55:54.783 E/Xposed  (14475): 	at com.example.zhang.myapplication.HookLoader.handleLoadPackage(l:70)
06-20 12:55:54.783 E/Xposed  (14475): 	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
06-20 12:55:54.783 E/Xposed  (14475): 	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
06-20 12:55:54.783 E/Xposed  (14475): 	at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
06-20 12:55:54.783 E/Xposed  (14475): 	at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
06-20 12:55:54.783 E/Xposed  (14475): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
06-20 12:55:54.783 E/Xposed  (14475): 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
06-20 12:55:54.783 E/Xposed  (14475): 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
06-20 12:55:54.783 E/Xposed  (14475): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1627)
06-20 12:55:54.783 E/Xposed  (14475): 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-20 12:55:54.783 E/Xposed  (14475): 	at android.os.Looper.loop(Looper.java:163)
06-20 12:55:54.783 E/Xposed  (14475): 	at android.app.ActivityThread.main(ActivityThread.java:6395)
06-20 12:55:54.783 E/Xposed  (14475): 	at java.lang.reflect.Method.invoke(Native Method)
06-20 12:55:54.783 E/Xposed  (14475): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
06-20 12:55:54.783 E/Xposed  (14475): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
06-20 12:55:54.783 E/Xposed  (14475): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
06-20 12:55:54.799 I/Xposed  (14475): Found wechat version:7.0.4
06-20 12:55:54.818 I/Xposed  (14475): load config successful
06-20 12:55:57.560 I/Xposed  (14475): Found wechat version:7.0.4
06-20 12:55:57.565 I/Xposed  (14475): Found wechat version:7.0.4

**Comment by skyun1314** [comment]
这报错日志牛逼。最新内核131应该修复了
