### ISSUE TITLE
未读信息清除无效

### ISSUE THREAD

**Issue by skyxieyi** [skyun1314/WeChat-plug-in#78]
点了标记已读，微信闪退，无效。
插件版本1.9.4 
手机小米note3 miui11 安卓9 面具+edxposed
另外建议这个标记已读能有快捷方式在微信界面，而不是在聊天界面设置菜单里操作

**Comment by skyun1314** [comment]
哦。下个版本修复。闪退可能是微信版本不对。
我的微信版本在百度云里面
 https://pan.baidu.com/s/1fCWiQG2nMo1SC5RHHrOzYg 提取码: si7m
