### ISSUE TITLE
微信6.6.6 框架不去作用

### ISSUE THREAD

**Issue by infinity-night** [skyun1314/WeChat-plug-in#8]
确认勾选了框架  并且手机已经重启多次   依然没有效果(主要测试的是 微信消息防撤回)

**Comment by skyun1314** [comment]
没有兼容6.6.6。有时间我在更新。最近事多

**Comment by infinity-night** [comment]
ok  现在兼容最好的是微信那个版本?

**Comment by skyun1314** [comment]
你从哪里看到的这个软件。下载地址都标注着。软件兼容版本啊
![image](https://user-images.githubusercontent.com/6341176/40152753-18fefb72-59b9-11e8-8ecb-d7eb41f649e3.png)

**Comment by infinity-night** [comment]
好的

**Comment by infinity-night** [comment]
你好  现在安装微信6.6.1  也不起作用

**Comment by skyun1314** [comment]
留下你联系方式。

**Comment by infinity-night** [comment]
QQ:2208428893
